export const NEXT_STEP = 'NEXT_STEP';
export const DETAILS_LOADED = 'DETAILS_LOADED';
export const PHONE_LOADED = 'PHONE_LOADED';
export const PHONE_VERIFIED = 'PHONE_VERIFIED';
export const CALLED_VERIFICATION = 'CALLED_VERIFICATION';
export const SENT_VERIFICATION = 'SENT_VERIFICATION';
export const ENABLE_VERIFICATION = 'ENABLE_VERIFICATION';
